REM Check PACK_VER.TXT and dont run if v.2.0

REM Prompt user, no turning back TDL will become non-functional.

REM Remove LaunchBox for DOS

REM Add DOSLFNM to Autoexec

REM Move all TDL to E:\TDL

REM Remove E:\files

REM Remove bad games, non-working -- free up space for conversion

REM Remove all OGG files for space

FIX all 1_Start/Run files to remove Gravis Ultrasound

FIX ALL 1_Start/Run files to remove 3dfx options

REM Run script to rename all E:\GAMES base folders to their long file name verison  - pull new script from private repo that uses eXoDOSv5.csv for LFN

REM Add E:\MyMenu

REM Add new E:\UTILS

REM Add new E:\PLAYERS

REM Add TheDraw

REM Add scrsavers

REM Add Music

REM Add GAMEANSI

REM What to do about AUTORUN.BAT

REM What to do about README.ANS (Launch version disable preview window to make it look like TDL)

REM Add ANSI

REM Add Apps

REM Add new fbsimple.raw, openinit.ram, 

REM Add CONFIG.SYS entries for Blackout

REM Add AUTOEXEC.BAT entries for blackout

REM Switch to NANSI.SYS

REM add C:\SDD 

REM Fix BUFFERS=

REM ADD AUTOEXEC UNIVBE SDD for LFB support and hide, work through high memory loading

REM Can we fix the stupid joystick initilization bug

REM SET Major Version number for E:\PACK_VER.TXT v.2.0




