REM Addon Cleanup
if NOT exist XcomUtil\flags\RunAddon.xcf goto noAddon
XcomUtil\Bin\BatRun XcomUtil\Addon Cleanup
:noAddon


REM Game Spacific Cleanup (Mostly Hybrid files)
if %XCOM%. == TFTD. goto tClean
:ufo
if exist maps\A_BASE00.MAP del maps\A_BASE*.MAP
if exist maps\ALART00.MAP  del maps\ALART*.MAP
if exist maps\ALSHIP00.MAP del maps\ALSHIP*.MAP
if exist maps\ATLAN00.MAP  del maps\ATLAN*.MAP
if exist maps\CARGO00.MAP  del maps\CARGO*.MAP
if exist maps\CORAL00.MAP  del maps\CORAL*.MAP
if exist maps\CRYPT01.MAP  del maps\CRYPT*.MAP
if exist maps\ENTRY00.MAP  del maps\ENTRY*.MAP
if exist maps\GAL01.MAP    del maps\GAL*.MAP
if exist maps\GRUNGE00.MAP del maps\GRUNGE*.MAP
if exist maps\HAMMER.MAP   del maps\HAMMER*.MAP
if exist maps\ISLAND00.MAP del maps\ISLAND*.MAP
if exist maps\LEVEL01.MAP  del maps\LEVEL*.MAP
if exist maps\LEVIATH.MAP  del maps\LEVIATH*.MAP
if exist maps\LINERT00.MAP del maps\LINER*.MAP
if exist maps\MSUNK00.MAP  del maps\MSUNK*.MAP
if exist maps\MU00.MAP     del maps\MU*.MAP
if exist maps\PIPES00.MAP  del maps\PIPES*.MAP
if exist maps\PLANE00.MAP  del maps\PLANE0*.MAP
if exist maps\PLANE10.MAP  del maps\PLANE1*.MAP
if exist maps\PLANE20.MAP  del maps\PLANE2*.MAP
if exist maps\PORT00.MAP   del maps\PORT*.MAP
if exist maps\SEABED00.MAP del maps\SEABED*.MAP
if exist maps\TRITON.MAP   del maps\TRITON*.MAP
if exist maps\UFO01.MAP    del maps\UFO0*.MAP
if exist maps\VOLC00.MAP   del maps\VOLC*.MAP
if exist maps\XBASES00.MAP del maps\XBASES*.MAP
if exist routes\A_BASE00.RMP  del routes\A_BASE*.RMP
if exist routes\ALART00.RMP   del routes\ALART*.RMP
if exist routes\ALSHIP00.RMP  del routes\ALSHIP*.RMP
if exist routes\ATLAN00.RMP   del routes\ATLAN*.RMP
if exist routes\CARGO00.RMP   del routes\CARGO*.RMP
if exist routes\CORAL00.RMP   del routes\CORAL*.RMP
if exist routes\CRYPT01.RMP   del routes\CRYPT*.RMP
if exist routes\ENTRY00.RMP   del routes\ENTRY*.RMP
if exist routes\GAL01.RMP     del routes\GAL*.RMP
if exist routes\GRUNGE00.RMP  del routes\GRUNGE*.RMP
if exist routes\HAMMER.RMP    del routes\HAMMER*.RMP
if exist routes\ISLAND00.RMP  del routes\ISLAND*.RMP
if exist routes\LEVEL01.RMP   del routes\LEVEL*.RMP
if exist routes\LEVIATH.RMP   del routes\LEVIATH*.RMP
if exist routes\LINERT00.RMP  del routes\LINER*.RMP
if exist routes\MSUNK00.RMP   del routes\MSUNK*.RMP
if exist routes\MU00.RMP      del routes\MU*.RMP
if exist routes\PIPES00.RMP   del routes\PIPES*.RMP
if exist routes\PLANE00.RMP   del routes\PLANE0*.RMP
if exist routes\PLANE10.RMP   del routes\PLANE1*.RMP
if exist routes\PLANE20.RMP   del routes\PLANE2*.RMP
if exist routes\PORT00.RMP    del routes\PORT*.RMP
if exist routes\SEABED00.RMP  del routes\SEABED*.RMP
if exist routes\TRITON.RMP    del routes\TRITON*.RMP
if exist routes\UFO01.RMP     del routes\UFO0*.RMP
if exist routes\VOLC00.RMP    del routes\VOLC*.RMP
if exist routes\XBASES00.RMP  del routes\XBASES*.RMP
if exist terrain\ASUNK.MCD    del terrain\ASUNK.*
if exist terrain\ATLANTIS.MCD del terrain\ATLANTIS.*
if exist terrain\CARGO1.MCD   del terrain\CARGO*.*
if exist terrain\CORAL.MCD    del terrain\CORAL.*
if exist terrain\CRYPT1.MCD   del terrain\CRYPT*.*
if exist terrain\DEBRIS.MCD   del terrain\DEBRIS.*
if exist terrain\DECKC.MCD    del terrain\DECKC*.*
if exist terrain\ENTRY.MCD    del terrain\ENTRY.*
if exist terrain\GRUNGE1.MCD  del terrain\GRUNGE*.*
if exist terrain\HAMMER.MCD   del terrain\HAMMER.*
if exist terrain\ISLAND1.MCD  del terrain\ISLAND*.*
if exist terrain\LEVIATH.MCD  del terrain\LEVIATH.*
if exist terrain\LINERA.MCD   del terrain\LINER*.*
if exist terrain\LOFTEMPS.DAT del terrain\LOFTEMPS.DAT
if exist terrain\MSUNK1.MCD   del terrain\MSUNK*.*
if exist terrain\MU.MCD       del terrain\MU.*
if exist terrain\ORGANIC1.MCD del terrain\ORGANIC*.*
if exist terrain\PIPES.MCD    del terrain\PIPES.*
if exist terrain\PORT01.MCD   del terrain\PORT*.*
if exist terrain\PSYNOM.MCD   del terrain\PSYNOM.*
if exist terrain\PYRAMID.MCD  del terrain\PYRAMID.*
if exist terrain\ROCKS.MCD    del terrain\ROCKS.*
if exist terrain\SAND.MCD     del terrain\SAND.*
if exist terrain\SCANG.DAT    del terrain\SCANG.DAT
if exist terrain\SEA.MCD      del terrain\SEA.*
if exist terrain\TRITON.MCD   del terrain\TRITON.*
if exist terrain\UEXT1.MCD    del terrain\UEXT*.*
if exist terrain\UFOBITS.MCD  del terrain\UFOBITS.*
if exist terrain\UINT1.MCD    del terrain\UINT*.*
if exist terrain\VOLC.MCD     del terrain\VOLC*.*
if exist terrain\WEEDS.MCD    del terrain\WEEDS.*
if exist terrain\XBASES01.MCD del terrain\XBASES*.*
if exist terrain\XBITS.MCD    del terrain\XBITS.*
goto dnHyCl
:tClean
if exist maps\avenger.map     del maps\avenger.map
if exist maps\culta00.map     del maps\culta*.map
if exist maps\desert00.map    del maps\desert*.map
if exist maps\forest00.map    del maps\forest*.map
if exist maps\jungle00.map    del maps\jungle*.map
if exist maps\lightnin.map    del maps\lightnin.map
if exist maps\map3.map        del maps\map3.map
if exist maps\map4.map        del maps\map4.map
if exist maps\mars00.map      del maps\mars*.map
if exist maps\mount00.map     del maps\mount*.map
if exist maps\pabduct.map     del maps\pabduct.map
if exist maps\pharvest.map    del maps\pharvest.map
if exist maps\polar00.map     del maps\polar*.map
if exist maps\pscout.map      del maps\pscout.map
if exist maps\temp.map        del maps\temp*.map
if exist maps\ubase_00.map    del maps\ubase_*.map
if exist maps\UFO1a.map       del maps\ufo1*.map
if exist maps\UFO_000.map     del maps\UFO_*.map
if exist maps\urban00.map     del maps\urban*.map
if exist maps\xbase_00.map    del maps\xbase_*.map
if exist routes\a_base16.rmp  del routes\a_base16.rmp
if exist routes\avenger.rmp   del routes\avenger.rmp
if exist routes\culta00.rmp   del routes\culta*.rmp
if exist routes\desert00.rmp  del routes\desert*.rmp
if exist routes\forest00.rmp  del routes\forest*.rmp
if exist routes\jungle00.rmp  del routes\jungle*.rmp
if exist routes\lightnin.rmp  del routes\lightnin.rmp
if exist routes\mars00.rmp    del routes\mars*.rmp
if exist routes\mount00.rmp   del routes\mount*.rmp
if exist routes\plane.rmp     del routes\plane.rmp
if exist routes\polar00.rmp   del routes\polar*.rmp
if exist routes\temp.rmp      del routes\temp*.rmp
if exist routes\ubase_00.rmp  del routes\ubase_*.rmp
if exist routes\ufo1a.rmp     del routes\ufo1a.rmp
if exist routes\ufo_000.rmp   del routes\ufo_*.rmp
if exist routes\urban00.rmp   del routes\urban*.rmp
if exist routes\xbase_00.rmp  del routes\xbase_*.rmp
if exist terrain\avenger.mcd  del terrain\avenger.*
if exist terrain\barn.mcd     del terrain\barn.*
if exist terrain\brain.mcd    del terrain\brain.*
if exist terrain\cultivat.mcd del terrain\cultivat.*
if exist terrain\desert.mcd   del terrain\desert.*
if exist terrain\forest.mcd   del terrain\forest.*
if exist terrain\frniture.mcd del terrain\frniture.*
if exist terrain\jungle.mcd   del terrain\jungle.*
if exist terrain\lightnin.mcd del terrain\lightnin.*
if exist terrain\mars.mcd     del terrain\mars.*
if exist terrain\mount.mcd    del terrain\mount.*
if exist terrain\polar.mcd    del terrain\polar.*
if exist terrain\roads.mcd    del terrain\roads.*
if exist terrain\u_base.mcd   del terrain\u_*.*
if exist terrain\UFO1.mcd     del terrain\ufo1.*
if exist terrain\urban.mcd    del terrain\urban.*
if exist terrain\xbase1.pck   del terrain\xbase1.pck
if exist terrain\xbase1.tab   del terrain\xbase1.tab
if exist terrain\xbase2.pck   del terrain\xbase2.pck
if exist terrain\xbase2.tab   del terrain\xbase2.tab
:dnHyCl

if exist geodata\world.xcu    del geodata\*.xcu
if exist geograph\BACK01.xsr  del geograph\*.xsr
if exist geograph\GRAPH.xbd   del geograph\*.xbd
if exist geograph\TEXTURE.xcu del geograph\*.xcu
if exist geograph\BACKG.xlb   del geograph\*.xlb
if exist geograph\INTICON.xpc del geograph\*.xpc
if exist geograph\GRAPHS.xsp  del geograph\*.xsp
if exist geograph\INTICON.xta del geograph\*.xta
if exist geoscape.exe         del geoscape.exe
if exist xcomutil.cfg         del xcomutil.cfg
if exist xcomutil.log         del xcomutil.log
if exist xcomutil.rms         del xcomutil.rms
if exist maps\a_base16.map    del maps\a_base16.map
if exist maps\alship18.map    del maps\alship18.map
if exist maps\barracud.map    del maps\barracud.map
if exist maps\crypt00.map     del maps\crypt00.map
if exist maps\fires.map       del maps\fires.map
if exist maps\grunge17.map    del maps\grunge17.map
if exist maps\interc.map      del maps\interc.map
if exist maps\level00.map     del maps\level00.map
if exist maps\manta.map       del maps\manta.map
if exist maps\noship.map      del maps\noship.map
if exist maps\xbase_21.map    del maps\xbase_21.map
if exist maps\ubase_16.map    del maps\ubase_16.map
if exist maps\plane.xcu       del maps\*.xcu
if exist maps\xcurandm.map    del maps\xcurandm.map
if exist missdat\geodata.dat  del missdat\geodata.dat
if exist missdat\mission2.dat del missdat\mission2.dat
if exist missdat\saveinfo.dat del missdat\saveinfo.dat
if exist routes\barracud.rmp  del routes\barracud.rmp
if exist routes\fires.rmp     del routes\fires.rmp
if exist routes\interc.rmp    del routes\interc.rmp
if exist routes\manta.rmp     del routes\manta.rmp
if exist routes\mu13.rmp      del routes\mu13.rmp
if exist routes\mu14.rmp      del routes\mu14.rmp
if exist routes\a_base16.rmp  del routes\a_base16.rmp
if exist routes\alship18.rmp  del routes\alship18.rmp
if exist routes\crypt00.rmp   del routes\crypt00.rmp
if exist routes\grunge17.rmp  del routes\grunge17.rmp
if exist routes\level00.rmp   del routes\level00.rmp
if exist routes\noship.rmp    del routes\noship.rmp
if NOT exist routes\avenger.rmp if exist routes\plane.rmp del routes\plane.rmp
if exist routes\plane.xcu     del routes\*.xcu
if exist routes\plane00.xcu   del routes\*.xcu
if exist routes\avenger.xcu   del routes\*.xcu
if exist routes\xcurandm.rmp  del routes\xcurandm.rmp
if exist sound\SAMPLE.xcu     del sound\*.xcu
if exist runxcom.bat          del runxcom.bat
if exist tactical.exe         del tactical.exe
if exist terrain\barracud.mcd del terrain\barracud.*
if exist terrain\fires.mcd    del terrain\fires.*
if exist terrain\interc.mcd   del terrain\interc.*
if exist terrain\manta.mcd    del terrain\manta.*
if exist terrain\plane.xcm    del terrain\*.xcm
if exist terrain\plane.xcp    del terrain\*.xcp
if exist terrain\plane.xct    del terrain\*.xct
if exist ufo2exe\tactical.xcu del ufo2exe\*.xcu
if exist ufoexe\geoscape.xcu  del ufoexe\*.xcu
if exist UFOGraph\ICONS.xbd   del UFOGraph\*.xbd
if exist UFOGraph\DETBLOB.xcu del UFOGraph\*.xcu
if exist UFOGraph\MOC1.xlb    del UFOGraph\*.xlb
if exist UFOGraph\D0.xlb      del UFOGraph\*.xlb
if exist UFOGraph\CURSOR.xpc  del UFOGraph\*.xpc
if exist UFOGraph\CURSOR.xta  del UFOGraph\*.xta
if exist UFOGraph\TAC00.xsr   del UFOGraph\*.xsr
if exist UFOGraph\MAN_0F0.xsp del UFOGraph\*.xsp
if exist units\BIGOBS.xpc     del units\*.xpc
if exist units\BIGOBS.xta     del units\*.xta
if exist terrain\planes.mcd   del terrain\planes.mcd
if exist terrain\planes.tab   del terrain\planes.tab
if exist terrain\planes.pck   del terrain\planes.pck
if exist XCLoader.exe 			  del xcloader.exe
if exist LastOp.bat           del LastOp.bat
if exist XcomUtil\LastOp.bat  del XcomUtil\LastOp.bat
if exist XcomUtil\ufo.xcu     del XcomUtil\ufo.xcu
if exist XcomUtil\terror.xcu  del XcomUtil\terror.xcu
if exist XcomUtil\flags\equiploc.xcu         del XcomUtil\flags\equiploc.xcu
if exist XcomUtil\flags\hybrdpth.xcu del XcomUtil\flags\hybrdpth.xcu
if exist XCUAFT\saveinfo.dat del XCUAFT\*.acb>>%redir%
if exist XCUAFT\saveinfo.dat del XCUAFT\*.bin>>%redir%
if exist XCUAFT\saveinfo.dat del XCUAFT\*.dat>>%redir%
if exist XCUAFT rmdir XCUAFT>>%redir%
if exist XCUAFT\nul rmdir XCUAFT>>%redir%
if exist XCUBEF\saveinfo.dat del XCUBEF\*.acb>>%redir%
if exist XCUBEF\saveinfo.dat del XCUBEF\*.bin>>%redir%
if exist XCUBEF\saveinfo.dat del XCUBEF\*.dat>>%redir%
if exist XCUBEF rmdir XCUBEF>>%redir%
if exist XCUBEF\nul rmdir XCUBEF>>%redir%
if exist xcomutil.exe del xcomutil.exe
if exist xcomutrt.exe del xcomutrt.exe
if exist XcomUtil\Bin\xcomutrt.exe del XcomUtil\Bin\xcomutrt.exe
if exist XcomUtil\Bin\find.com del XcomUtil\Bin\find.com
if exist XcomUtil\Bin\sdump.exe del XcomUtil\Bin\sdump.exe
if exist XcomUtil\Bin\xcopy.exe del XcomUtil\Bin\xcopy.exe
if exist XcomUtil\Bin\ResFix.exe del XcomUtil\Bin\resfix.exe
if exist XcomUtil\Bin\ResInfo.exe del XcomUtil\Bin\ResInfo.exe
if exist XcomUtil\Bin\BatRun.exe del XcomUtil\Bin\BatRun.exe
if exist OldBatch.bat if exist ufocd.bat copy /y OldBatch.bat ufocd.bat
if exist OldBatch.bat if exist terror.bat copy /y OldBatch.bat terror.bat
if exist OldBatch.bat echo.
if exist OldBatch.bat echo  !!!!!!! XcomUtil Steam Menu Removed !!!!!!!
if exist OldBatch.bat echo  to re-enable run XcomUtil\SteamSetup.bat from the Steam folder.
if exist debug.txt del debug.txt
REM if exist XcomUtil\debug.txt del XcomUtil\debug.txt

