@CLS
@ECHO OFF
ECHO *************************************************************************
ECHO     LANDS OF LORE: THE THRONE OF CHAOS CDROM UPDATE TO VERSION 1.02
ECHO *************************************************************************
ECHO.       
ECHO This update fixes several minor bugs including the problems experienced
ECHO by some users of very fast machines (Pentiums, 66's and very few 33's).
ECHO.  
ECHO.
ECHO Patch installation instructions for upgrade to Version  
ECHO -------------------------------------------------------------
ECHO.
ECHO   1) Copy the following files into the directory that contain 
ECHO      the Hard disk files for LANDS OF LORE CD-ROM.
ECHO.
ECHO      PATCH.RTP
ECHO.     PATCH.EXE
ECHO.
ECHO   2) Type PATCH at the DOS prompt and press ENTER.
ECHO.  
ECHO   3) Wait until the patch process completes and then play normally.
ECHO.
ECHO.
ECHO.      
PAUSE
CLS
ECHO What to do if the patch program does not seem to work.
ECHO -------------------------------------------------------------
ECHO.
ECHO.
ECHO This patch actually updates the LANDS OF LORE CDROM files
ECHO (now moved to your hard drive) only if they have not been 
ECHO altered by cheat/hex programs.  
ECHO. 
ECHO If the patch will not work, you probably already have an updated
ECHO version of LANDS OF LORE CDROM and do not need to repatch the program.  
ECHO The version number is located on the bottom right hand corner of your 
ECHO title screen.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
PAUSE
CLS
ECHO If you are experiencing Audio/Sound card problems.
ECHO -------------------------------------------------------------
ECHO.
ECHO.
ECHO If you are having trouble playing digitized sound with your Soundblaster 
ECHO compatible sound card please try the following.
ECHO.
ECHO   * Make sure that your AUTOEXEC.BAT file contains the "SET BLASTER=....."
ECHO       command to indicate what settings your sound card is configured for.
ECHO.
ECHO     The "SET BLASTER" command is configured as:
ECHO.
ECHO                     "SET BLASTER=A220 I7 D1 T1"
ECHO.
ECHO     Where:  Axxx = address of soundcard      (Default = 220)
ECHO             Ix   = interrupt of soundcard    (Default = 7)
ECHO             Dx   = DMA channel               (Default = 1)
ECHO             Tx   = Type of card              (Default = 1 for Soundblaster)   
ECHO.
ECHO     ** Hand of Fate will work with various interrupt, address, and DMA
ECHO     settings.   Just be sure they match the ones on your Soundblaster 
ECHO     compatible card.
ECHO.
PAUSE
CLS
ECHO.
ECHO Where to reach us if you need help.
ECHO -------------------------------------------------------------
ECHO.
ECHO You can receive further help by contacting Westwood Studios technical 
ECHO support at 1-714-833-1999.   Westwood also maintains a Bulletin Board System
ECHO which operates at 300 - 14,400 baud.  The number to the Westwood BBS is
ECHO 702-368-2319.
ECHO.
ECHO Thank you for your support.
ECHO.
ECHO Westwood Studios
ECHO.
ECHO.
ECHO.
ECHO.

