

:intro
@cls
@E:\GAMES\WORMSUNI\WORMSRE\Worms\bin\black.exe
SET dos4g=quiet
SET wormscfg=E:\GAMES\WORMSUNI\WORMSRE\Worms\worms.cfg
SET wormscd=D:
@D:\fmv\play D:\fmv\logo2.avi
@D:\fmv\play D:\fmv\logo1.avi
@D:\fmv\play D:\fmv\armup.avi
@E:\GAMES\WORMSUNI\WORMSRE\Worms\bin\black.exe
@E:\GAMES\WORMSUNI\WORMSRE\Worms\bin\wrms
@goto end
:skip
@cls
@E:\GAMES\WORMSUNI\WORMSRE\Worms\bin\black.exe
SET dos4g=quiet
SET wormscfg=E:\GAMES\WORMSUNI\WORMSRE\Worms\worms.cfg
SET wormscd=D:
@E:\GAMES\WORMSUNI\WORMSRE\Worms\bin\wrms
:end
