ECHO OFF
CLS
REM Common 5-1/4 and 3-1/2 copying of disk 1/2

SET SRC=%1
IF EXIST %SRC%:MS.BAT COPY %SRC%:MS.BAT \MS.BAT
GOTO DISKC1A

:DISKC1
CLS
ECHO INSERT DISK #1 INTO DRIVE %SRC%
PAUSE
:DISKC1A
IF NOT EXIST %SRC%:MS.EXE GOTO DISKC1
ECHO COPYING MEAN STREETS DISK #1 FILES...
COPY %SRC%:*.*

:DISKC2
CLS
ECHO INSERT DISK #2 INTO DRIVE %SRC%
PAUSE
IF NOT EXIST %SRC%:FLIGHT.ACC GOTO DISKC2
ECHO COPYING MEAN STREETS DISK #2 FILES...
COPY %SRC%:*.*

REM Check for a file on the 3-1/2 that wouldn't be on the 5-1/4...

IF EXIST %SRC%:\VPHONE.ACC GOTO DISK33

REM Come here to do the rest of the 5-1/4 copying

:DISK53
CLS
ECHO INSERT DISK #3 INTO DRIVE %SRC%
PAUSE
IF NOT EXIST %SRC%:VPHONE.ACC GOTO DISK53
ECHO COPYING MEAN STREETS DISK #3 FILES...
COPY %SRC%:*.*

:DISK54
CLS
ECHO INSERT DISK #4 INTO DRIVE %SRC%
PAUSE
IF NOT EXIST %SRC%:BACKDRP1.ACC GOTO DISK54
ECHO COPYING MEAN STREETS DISK #4 FILES...
COPY %SRC%:*.*

:DISK55
CLS
ECHO INSERT DISK #5 INTO DRIVE %SRC%
PAUSE
IF NOT EXIST %SRC%:BACKDRP2.ACC GOTO DISK55
ECHO COPYING MEAN STREETS DISK #5 FILES...
COPY %SRC%:*.*

:DISK56
CLS
ECHO INSERT DISK #6 INTO DRIVE %SRC%
PAUSE
IF NOT EXIST %SRC%:ROOM0.ACC GOTO DISK56
ECHO COPYING MEAN STREETS DISK #6 FILES...
COPY %SRC%:*.*
COPY %SRC%:MS.BAT \MS.BAT

GOTO DONE

REM Come here to do the 3-1/2 disk copying

:DISK33
CLS
ECHO INSERT DISK #3 INTO DRIVE %SRC%
PAUSE
IF NOT EXIST %SRC%:BACKDRP1.ACC GOTO DISK33
ECHO COPYING MEAN STREETS DISK #3 FILES...
COPY %SRC%:*.*

:DONE
CLS

ECHO INSTALLATION COMPLETE!

:EXIT
