echo off
cls
echo		Ensure that the  WRITE PROTECT  TAB  is  in  the  WRITE 
echo		position.
echo.
echo.
echo		After completing level one for the first time, you will 
echo		enter a room with various potions.  Drinking ANY potion
echo		will open the door that allows you to enter  the second
echo		level.
echo.
echo.
echo		This message will NOT appear again, after using install
echo	        program.
pause
rename install1.exe install.exe
rename prince1.exe prince.exe
install.exe 
rem                             "6th, October 1992"
